project_name: protoc-gen-go_temporal
before:
  hooks:
    - go mod tidy
builds:
  - id: protoc-gen-go_temporal
    binary: protoc-gen-go_temporal
    main: ./cmd/protoc-gen-go_temporal
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"
archives:
  - files:
      - LICENSE.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: cludden
    name: protoc-gen-go-temporal
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
brews:
  - repository:
      owner: cludden
      name: homebrew-formula
    homepage: https://github.com/cludden/protoc-gen-go-temporal
    description: protoc-gen-go_temporal - a protoc plugin for generating Temporal clients, workers, and clis in go from protobuf schemas
    license: MIT