all: false
dir: '{{.InterfaceDir}}'
filename: mocks.go
force-file-write: true
formatter: goimports
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}'
recursive: false
replace-type:
  go.temporal.io/sdk/internal:
    Context:
      pkg-path: go.temporal.io/sdk/workflow
      type-name: Context
require-template-schema-exists: true
template: testify
template-schema: '{{.Template}}.schema.json'
template-data:
  unroll-variadic: true
packages:
  github.com/cludden/protoc-gen-go-temporal/gen/example/v1:
    config:
      dir: mocks/example/v1
      pkgname: examplev1mocks
    interfaces:
      CreateFooRun: {}
      ExampleClient: {}
      UpdateFooProgressHandle: {}
  github.com/cludden/protoc-gen-go-temporal/gen/test/simple/v1:
    config:
      dir: mocks/test/simple/v1
      pkgname: simplev1mocks
    interfaces:
      SimpleWorkflowFunctions: {}
  github.com/cludden/protoc-gen-go-temporal/gen/test/xnserr/v1:
    config:
      dir: mocks/test/xnserr/v1
      pkgname: xnserrv1mocks
    interfaces:
      ServerClient: {}
      SleepRun: {}
  go.temporal.io/sdk/client:
    config:
      dir: mocks/go.temporal.io/sdk/client
      pkgname: clientmocks
    interfaces:
      Client: {}
      WorkflowRun:
        configs:
          - replace-type:
              go.temporal.io/sdk/internal:
                Context:
                  pkg-path: go.temporal.io/sdk/workflow
                  type-name: Context
                WorkflowRunGetOptions:
                  pkg-path: go.temporal.io/sdk/client
                  type-name: WorkflowRunGetOptions
