disable-version-string: true
issue-845-fix: true
resolve-type-alias: false
with-expecter: true
packages:
  github.com/cludden/protoc-gen-go-temporal/gen/example/v1:
    config:
      replace-type:
        - go.temporal.io/sdk/internal=go.temporal.io/sdk/client
    interfaces:
      CreateFooRun: {}
      ExampleClient: {}
      UpdateFooProgressHandle: {}
  github.com/cludden/protoc-gen-go-temporal/gen/test/simple/v1:
    config:
      replace-type:
        - go.temporal.io/sdk/internal=go.temporal.io/sdk/workflow
    interfaces:
      SimpleWorkflowFunctions: {}
  github.com/cludden/protoc-gen-go-temporal/gen/test/xnserr/v1:
    config:
      outpkg: xnserrv1mocks
      replace-type:
        - go.temporal.io/sdk/internal=go.temporal.io/sdk/client
    interfaces:
      ServerClient: {}
      SleepRun: {}
  go.temporal.io/sdk/internal:
    config:
      dir: mocks/go.temporal.io/sdk/clientutils
      outpkg: clientutils
      replace-type:
        - go.temporal.io/sdk/internal=go.temporal.io/sdk/client
    interfaces:
      WorkflowRun: {}
  go.temporal.io/sdk/client:
    config:
      replace-type:
        - go.temporal.io/sdk/internal=go.temporal.io/sdk/client
    interfaces:
      Client: {}
