// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package workermocks

import (
	"github.com/nexus-rpc/sdk-go/nexus"
	mock "github.com/stretchr/testify/mock"
	"go.temporal.io/sdk/activity"
	"go.temporal.io/sdk/workflow"
)

// NewMockRegistry creates a new instance of MockRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistry {
	mock := &MockRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegistry is an autogenerated mock type for the Registry type
type MockRegistry struct {
	mock.Mock
}

type MockRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistry) EXPECT() *MockRegistry_Expecter {
	return &MockRegistry_Expecter{mock: &_m.Mock}
}

// RegisterActivity provides a mock function for the type MockRegistry
func (_mock *MockRegistry) RegisterActivity(a interface{}) {
	_mock.Called(a)
	return
}

// MockRegistry_RegisterActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterActivity'
type MockRegistry_RegisterActivity_Call struct {
	*mock.Call
}

// RegisterActivity is a helper method to define mock.On call
//   - a interface{}
func (_e *MockRegistry_Expecter) RegisterActivity(a interface{}) *MockRegistry_RegisterActivity_Call {
	return &MockRegistry_RegisterActivity_Call{Call: _e.mock.On("RegisterActivity", a)}
}

func (_c *MockRegistry_RegisterActivity_Call) Run(run func(a interface{})) *MockRegistry_RegisterActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistry_RegisterActivity_Call) Return() *MockRegistry_RegisterActivity_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRegistry_RegisterActivity_Call) RunAndReturn(run func(a interface{})) *MockRegistry_RegisterActivity_Call {
	_c.Run(run)
	return _c
}

// RegisterActivityWithOptions provides a mock function for the type MockRegistry
func (_mock *MockRegistry) RegisterActivityWithOptions(a interface{}, options activity.RegisterOptions) {
	_mock.Called(a, options)
	return
}

// MockRegistry_RegisterActivityWithOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterActivityWithOptions'
type MockRegistry_RegisterActivityWithOptions_Call struct {
	*mock.Call
}

// RegisterActivityWithOptions is a helper method to define mock.On call
//   - a interface{}
//   - options activity.RegisterOptions
func (_e *MockRegistry_Expecter) RegisterActivityWithOptions(a interface{}, options interface{}) *MockRegistry_RegisterActivityWithOptions_Call {
	return &MockRegistry_RegisterActivityWithOptions_Call{Call: _e.mock.On("RegisterActivityWithOptions", a, options)}
}

func (_c *MockRegistry_RegisterActivityWithOptions_Call) Run(run func(a interface{}, options activity.RegisterOptions)) *MockRegistry_RegisterActivityWithOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 activity.RegisterOptions
		if args[1] != nil {
			arg1 = args[1].(activity.RegisterOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRegistry_RegisterActivityWithOptions_Call) Return() *MockRegistry_RegisterActivityWithOptions_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRegistry_RegisterActivityWithOptions_Call) RunAndReturn(run func(a interface{}, options activity.RegisterOptions)) *MockRegistry_RegisterActivityWithOptions_Call {
	_c.Run(run)
	return _c
}

// RegisterNexusService provides a mock function for the type MockRegistry
func (_mock *MockRegistry) RegisterNexusService(service *nexus.Service) {
	_mock.Called(service)
	return
}

// MockRegistry_RegisterNexusService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterNexusService'
type MockRegistry_RegisterNexusService_Call struct {
	*mock.Call
}

// RegisterNexusService is a helper method to define mock.On call
//   - service *nexus.Service
func (_e *MockRegistry_Expecter) RegisterNexusService(service interface{}) *MockRegistry_RegisterNexusService_Call {
	return &MockRegistry_RegisterNexusService_Call{Call: _e.mock.On("RegisterNexusService", service)}
}

func (_c *MockRegistry_RegisterNexusService_Call) Run(run func(service *nexus.Service)) *MockRegistry_RegisterNexusService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *nexus.Service
		if args[0] != nil {
			arg0 = args[0].(*nexus.Service)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistry_RegisterNexusService_Call) Return() *MockRegistry_RegisterNexusService_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRegistry_RegisterNexusService_Call) RunAndReturn(run func(service *nexus.Service)) *MockRegistry_RegisterNexusService_Call {
	_c.Run(run)
	return _c
}

// RegisterWorkflow provides a mock function for the type MockRegistry
func (_mock *MockRegistry) RegisterWorkflow(w interface{}) {
	_mock.Called(w)
	return
}

// MockRegistry_RegisterWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterWorkflow'
type MockRegistry_RegisterWorkflow_Call struct {
	*mock.Call
}

// RegisterWorkflow is a helper method to define mock.On call
//   - w interface{}
func (_e *MockRegistry_Expecter) RegisterWorkflow(w interface{}) *MockRegistry_RegisterWorkflow_Call {
	return &MockRegistry_RegisterWorkflow_Call{Call: _e.mock.On("RegisterWorkflow", w)}
}

func (_c *MockRegistry_RegisterWorkflow_Call) Run(run func(w interface{})) *MockRegistry_RegisterWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistry_RegisterWorkflow_Call) Return() *MockRegistry_RegisterWorkflow_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRegistry_RegisterWorkflow_Call) RunAndReturn(run func(w interface{})) *MockRegistry_RegisterWorkflow_Call {
	_c.Run(run)
	return _c
}

// RegisterWorkflowWithOptions provides a mock function for the type MockRegistry
func (_mock *MockRegistry) RegisterWorkflowWithOptions(w interface{}, options workflow.RegisterOptions) {
	_mock.Called(w, options)
	return
}

// MockRegistry_RegisterWorkflowWithOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterWorkflowWithOptions'
type MockRegistry_RegisterWorkflowWithOptions_Call struct {
	*mock.Call
}

// RegisterWorkflowWithOptions is a helper method to define mock.On call
//   - w interface{}
//   - options workflow.RegisterOptions
func (_e *MockRegistry_Expecter) RegisterWorkflowWithOptions(w interface{}, options interface{}) *MockRegistry_RegisterWorkflowWithOptions_Call {
	return &MockRegistry_RegisterWorkflowWithOptions_Call{Call: _e.mock.On("RegisterWorkflowWithOptions", w, options)}
}

func (_c *MockRegistry_RegisterWorkflowWithOptions_Call) Run(run func(w interface{}, options workflow.RegisterOptions)) *MockRegistry_RegisterWorkflowWithOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 workflow.RegisterOptions
		if args[1] != nil {
			arg1 = args[1].(workflow.RegisterOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRegistry_RegisterWorkflowWithOptions_Call) Return() *MockRegistry_RegisterWorkflowWithOptions_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRegistry_RegisterWorkflowWithOptions_Call) RunAndReturn(run func(w interface{}, options workflow.RegisterOptions)) *MockRegistry_RegisterWorkflowWithOptions_Call {
	_c.Run(run)
	return _c
}
