[settings]
experimental = true

[tools]
changie = "latest"
"github:bufbuild/buf" = "1.56.0"
"github:cludden/protoc-gen-go-temporal" = "latest"
"github:golangci/golangci-lint" = "2.3.0"
"github:protocolbuffers/protobuf-go" = "1.36.8"
"github:temporalio/cli" = "1.3.0"
"github:vektra/mockery" = "3.5.1"
go = "1.23.6"
"go:github.com/alta/protopatch/cmd/protoc-gen-go-patch" = "v0.5.3"
"go:github.com/mfridman/tparse" = "v0.17.0"
goreleaser = "2.15.4"
node = "latest"
protoc = "latest"
